---
- name: "TASK 1 - ROUTING TASK"
  hosts: routers
  connection: network_cli
  gather_facts: false
  tasks:

  - name: "TASK 1 - Routing EIGRP"
    cisco.ios.ios_config:
      lines: "{{ item }}"
      parents:
        - router eigrp 1
    with_items: "{{ eigrp }}"

- name: "TASK 2 - ROUTING TASK"
  hosts: defroute
  connection: network_cli
  gather_facts: false
  tasks:

  - name: "TASK 2 - Default Route"
    cisco.ios.ios_config:
      lines: "{{ item }}"
    with_items: "{{ default_route }}"
