- name: "TASK 2 - ROUTING TASK"
  hosts: routers
  connection: network_cli
  gather_facts: false
  tasks:

    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified

